parse_config:

  layer_legend_map:
    Navigation:       NAV
    Number/Symbol:    NUM

  raw_binding_map:
    '&bootloader':    BOOT
    '&soft_off':      SOFT OFF
    '&caps_word':     Caps Word
    '&macro_grave3':  '```'
    '&macro_nequal':  <  >
    '&macro_qu':      QU
    '&trans':         ''

    #default
    DEF_TOG_MIC:      Mute Mic
    DEF_SHA_SCR:      Share Screen
    DEF_UNDO:         Undo
    DEF_REDO:         Redo
    DEF_BACK_WD:      Back Word
    DEF_STICKYS:      Sticky Shift

    # navigation
    NAV_SEL_AL:       SELECT ALL
    NAV_SEL_LI:       SEL LINE
    NAV_TAB_LE:       PREV TAB
    NAV_TAB_RI:       NEXT TAB
    NAV_CUT:          CUT
    NAV_COPY:         {t: COPY, h: R Shift}
    NAV_PASTE:        PASTE
    NAV_TAB:          {t: TAB, h: Ctrl}
    NAV_SWAP:         {t: SWAP, h: Shift}
    NAV_INCOG:        {t: INCOG, h: Alt}
    NAV_SCREENS:      {t: SCREEN SHOT, h: Win}
    NAV_CLO_TAB:      CLOSE TAB
    NAV_TAB_RO:       REOPEN TAB
    NAV_TAB_NE:       NEW TAB
    NAV_CLO_APP:      CLOSE APP
    NAV_SMILEY:       $$mdi:emoticon-happy-outline$$
    NAV_DELWRD:       DELETE WORD
    NAV_SWI_LE:       {t: $$mdi:arrow-left$$, s: SWITCH}
    NAV_SWI_RI:       {t: $$mdi:arrow-right$$, s: SWITCH}
    NAV_THREAD:       SLACK THREAD

    # number
    NUM_MINUS:        {t: '-', h: Ctrl}
    NUM_UNDER:        {t: '_', h: Shift}
    NUM_STAR:         {t: '*', h: Alt}
    NUM_PERCENT:      {t: '%', h: Win}
    NUM_PIPE:         {t: '|', h: R Shift}
    NUM_AMPS:         {t: '&', s: '£'}
    NUM_N0:           '0'
    NUM_N1:           '1'
    NUM_N2:           '2'
    NUM_N3:           '3'
    NUM_N4:           '4'
    NUM_N5:           {t: '5', s: ','}
    NUM_N6:           {t: '6', s: '.'}
    NUM_N7:           '7'
    NUM_N8:           '8'
    NUM_N9:           '9'

    # miscellaneous
    MIS_VOL_DN:       $$mdi:volume-minus$$
    MIS_VOL_MU:       $$mdi:volume-mute$$
    MIS_VOL_UP:       $$mdi:volume-plus$$
    MIS_MUT_MIC:      $$mdi:microphone-off$$
    MIS_BT_1:         {t: $$mdi:bluetooth-connect$$, s: '1'}
    MIS_BT_2:         {t: $$mdi:bluetooth-connect$$, s: '2'}
    MIS_BT_3:         {t: $$mdi:bluetooth-connect$$, s: '3'}
    MIS_CAD:          C  A  D
    MIS_BRI_DN:       $$mdi:weather-night$$
    MIS_BRI_UP:       $$mdi:weather-sunny$$
    MIS_BITWAR:       BIT WAR 
    MIS_GENERAT:      GEN PWD
    MIS_SLEEP:        SLEEP

    # UK symbols
    UK_HASH:          '#'
    UK_DQT:           '"'
    UK_AT:            '@'
    UK_GRAVE:         '`'
    UK_EURO:          €

  zmk_combos:
    combo_grave3:     {a: top, o: 0.3}
    combo_q:          {a: top, o: 0.3}
    combo_z:          {a: bottom, o: 0.3}
    combo_nequal:     {a: bottom, o: 0.3}
    combo_esc:        {draw_separate: true}
    combo_enter:      {draw_separate: true}
    combo_undo:       {draw_separate: true}
    combo_redo:       {draw_separate: true}
    combo_tog_mic:    {draw_separate: true}
    combo_share:      {draw_separate: true}
    combo_rbrc:       {draw_separate: true}
    combo_lbrc:       {draw_separate: true}
    combo_rpar:       {draw_separate: true}
    combo_lpar:       {draw_separate: true}
    combo_rbkt:       {draw_separate: true}
    combo_lbkt:       {draw_separate: true}
    combo_ssl:        {draw_separate: true}
    combo_ssr:        {draw_separate: true}
    combo_capsword:   {draw_separate: true}
    combo_capslock:   {draw_separate: true}
    combo_bspc:       {draw_separate: true}
    combo_backword:   {draw_separate: true}

  zmk_keycode_map:
    SPACE:            $$mdi:keyboard-space$$
    LCTL:             Ctrl
    LALT:             Alt
    LGUI:             Win
    LSFT:             Shift
    RSFT:             R Shift
    ESC:              Esc
    DEL:              DELETE
    F2:               RENAME
    F6:               URL BAR
    F11:              FULL SCREEN
    F12:              DEV TOOLS
    F21:              VISUAL
    F22:              GRID
    K_APP:            {type: held}
    ENTER:            Enter
    C_PLAY:           $$mdi:play-pause$$
    C_PREV:           $$mdi:skip-previous$$
    C_NEXT:           $$mdi:skip-next$$
    BT_CLR:           {t: $$mdi:bluetooth-connect$$, s: 'CLEAR'}

    UP:               {t: $$mdi:arrow-up$$, s: PG  Up}
    DOWN:             {t: $$mdi:arrow-down$$, s: PG  Down}
    LEFT:             {t: $$mdi:arrow-left$$, s: Home}
    RIGHT:            {t: $$mdi:arrow-right$$, s: End}

    # defaults
    AMPS:             '&'
    NUBS:             \
    BSLH:             \
    CAPS:             Caps Lock
    CARET:            ^
    COLON:            ':'
    COMMA:            ','
    DOLLAR:           $
    DOT:              '.'
    EQUAL:            '='
    EXCL:             '!'
    FSLH:             /
    GRAVE:            '`'
    GT:               '>'
    HASH:             '#'
    LBKT:             '['
    LBRC:             '{'
    LPAR:             (
    LT:               <
    MINUS:            '-'
    PERCENT:          '%'
    PIPE2:            '|'
    PLUS:             +
    PRCNT:            '%'
    QMARK:            '?'
    RBKT:             ']'
    RBRC:             '}'
    RPAR:             )
    SEMI:             ;
    SQT:              ''''
    STAR:             '*'
    TILDE2:           '~'
    UNDER:            _

draw_config:
  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  dark_mode: false

  # Custom CSS
  svg_extra_style: |
    .ghost {
      display: none !important;
    }
  
  layer_legend_map: dict[Navigation, Nav] = {}