# configuration for https://github.com/caksoylar/keymap-drawer
parse_config:
    zmk_combos:
      c_w:    {align: bottom, draw_separate: true}

    zmk_keycode_map:
      LCTRL: Ctrl
      RCTRL: Ctrl
      LALT: Alt
      RALT: Alt
      LGUI: Gui
      RGUI: Gui
      LSHFT: Shift
      RSHFT: Shift
      ESC: Esc
      SPACE: ␣
      BSPC: ⌫
      RET: ⏎
      TAB: ↹
      DEL: ⌦

      PG_UP: Page Up
      PG_DN: Page Down
      INS: Insert
      HOME: Home
      END: End
      CAPS: Caps Lock
      PSCRN: Print Scrn
      PAUSE_BREAK: Pause Break

      UP: ↑
      DOWN: ↓
      LEFT: ←
      RIGHT: →

      C_PP: ⏯
      C_NEXT: ⏭️
      C_PREV: ⏮️

      # defaults
      AMPERSAND: '&'
      AMPS: '&'
      APOS: "'"
      APOSTROPHE: "'"
      ASTERISK: '*'
      ASTRK: '*'
      AT: '@'
      AT_SIGN: '@'
      BACKSLASH: \
      BSLH: \
      CARET: ^
      COLON: ':'
      COMMA: ','
      DLLR: $
      DOLLAR: $
      DOT: .
      DOUBLE_QUOTES: '"'
      DQT: '"'
      EQUAL: '='
      EXCL: '!'
      EXCLAMATION: '!'
      FSLH: /
      GRAVE: '`'
      GREATER_THAN: '>'
      GT: '>'
      HASH: '#'
      LBKT: '['
      LBRC: '{'
      LEFT_BRACE: '{'
      LEFT_BRACKET: '['
      LEFT_PARENTHESIS: (
      LESS_THAN: <
      LPAR: (
      LT: <
      MINUS: '-'
      NON_US_BACKSLASH: \
      NON_US_BSLH: '|'
      NON_US_HASH: '#'
      NUHS: '#'
      PERCENT: '%'
      PERIOD: .
      PIPE: '|'
      PIPE2: '|'
      PLUS: +
      POUND: '#'
      PRCNT: '%'
      QMARK: '?'
      QUESTION: '?'
      RBKT: ']'
      RBRC: '}'
      RIGHT_BRACE: '}'
      RIGHT_BRACKET: ']'
      RIGHT_PARENTHESIS: )
      RPAR: )
      SEMI: ;
      SEMICOLON: ;
      SINGLE_QUOTE: ''''
      SLASH: /
      SQT: ''''
      STAR: '*'
      TILDE: '~'
      TILDE2: '~'
      UNDER: _
      UNDERSCORE: _