parse_config:
  raw_binding_map:
    '&lt NAV SPACE':  {t: SPACE, h: NAV}
    '&lt NUM E':      {t: E, h: NUM}

    '&bootloader':    'BOOT'
    '&macro_grave3':  '```'
    '&macro_nequal':  '<>'
    '&mm_new_tab':    'NEW TAB'
    '&mm_sqt_sqt':    "'"
    'A_BULLHORN':     'BH'
    'A_CALENDAR':     'CAL'
    'A_GLADMIN':      'ADMIN'
    'A_INBOX':        'INBOX'
    'A_SLACK':        'SLACK'
    'CAD':            'C+A+D'
    'CON_ONE':        'BT1'
    'CON_THREE':      'BT3'
    'CON_TWO':        'BT2'
    'DEL_WORD':       'DEL WORD'
    'DESK_L':         '← DESK'
    'DESK_R':         'DESK →'
    'KILL':           'KILL'
    'NEW_LINE':       'NEW LINE'
    'SCREEN_SHOT':    'SSHOT'
    'SHO_APP_SEL':    'SWAP'
    'SHO_COPY':       'COPY'
    'SHO_CUT':        'CUT'
    'SHO_PASTE':      'PASTE'
    'SHO_REDO':       'REDO'
    'SHO_SEL_ALL':    'SEL ALL'
    'SHO_UNDO':       'UNDO' 
    'SLACK_DN':       'SLACK ↓'
    'SLACK_UP':       'SLACK ↑'
    'TAB_NEXT':       'TAB →'
    'TAB_PREV':       '← TAB'
    'UK_AT':          '"'
    'UK_DQT':         '@'
    'UK_GRAVE':       '`'
    'UK_HASH':        '#'
    'UK_POUND':       '£'

zmk_keycode_map:
    # custom mappings
    LCTRL:            Ctrl
    RCTRL:            Ctrl
    LALT:             Alt
    RALT:             Alt
    LGUI:             Win
    RGUI:             Win
    LSHFT:            Shift
    RSHFT:            Shift
    ESC:              Esc
    SPACE:            ␣
    BSPC:             ⌫

draw_config:
  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  dark_mode: auto