parse_config:
  raw_binding_map:
    '&mm_sqt_sqt': "'"
    'REDO': 'REDO'
    'UNDO': 'UNDO' 
    'UK_AT': '"'
    'UK_DQT': '@'
    'UK_HASH': '#'
    'UK_POUND': '£'
    '&kp GRAVE': '`'
    '&bootloader': 'BOOT'
    'CON_ONE': 'BT1'
    'CON_TWO': 'BT2'
    'CON_THREE': 'BT3'
    'CAD': 'C+A+D'
    'SCREEN_SHOT': 'S SHOT'
    'DESK_L': 'DESK  L'
    'DESK_R': 'DESK R'
    'KILL': 'KILL'
    'A_INBOX': 'INBOX'
    'A_SLACK': 'SLACK'
    'A_GLADMIN': 'ADMIN'
    'A_BULLHORN': 'BH'
    'A_CALENDAR': 'CAL'