parse_config:
  raw_binding_map:
    '&bootloader':    BOOT
    '&caps_word':     Caps Word
    '&macro_grave3':  '```'
    '&macro_nequal':  <  >
    '&trans':         ''
    '&none':          {type: ghost}
    '&lt NAV SPACE':  {t: SPACE, h: NAV}
    '&lt NUM E':      {t: E, h: NUM}
    
    THUMB:            {type: held}

    # navigation
    NAV_SEL_AL:       SEL ALL
    NAV_SEL_LE:       SEL PREV
    NAV_SEL_RI:       SEL NEXT
    NAV_SEL_LI:       SEL LINE
    NAV_TAB_LE:       PREV TAB
    NAV_TAB_RI:       NEXT TAB
    NAV_CUT:          CUT
    NAV_COPY:         COPY
    NAV_PASTE:        PASTE
    NAV_SWAP:         {t: SWAP, h: Shift}
    NAV_TAB:          {t: TAB, h: Ctrl}
    NAV_TAB_CL:       {t: CLOSE TAB, h: Alt}
    NAV_TAB_RO:       {t: REOPEN TAB, h: Win}
    NAV_TAB_NE:       NEW TAB
    NAV_CLOSE:        CLOSE
    NAV_SMILEY:       SMILEY
    NAV_DELWRD:       DEL WORD
    NAV_SWI_LE:       SWITCH LEFT
    NAV_SWI_RI:       SWITCH RIGHT

    # number
    NUM_N0:           '0'
    NUM_N1:           '1'
    NUM_N2:           '2'
    NUM_N3:           '3'
    NUM_N4:           '4'
    NUM_N5:           '5'
    NUM_N6:           '6'
    NUM_N7:           '7'
    NUM_N8:           '8'
    NUM_N9:           '9'

  zmk_keycode_map:
    LCTL:             Ctrl
    LALT:             Alt
    LGUI:             Win
    LSFT:             Shift
    ESC:              Esc

    F2:               RENAME
    F6:               URL BAR
    F11:              FULL SCREEN
    F12:              DEV TOOLS

    ENTER:            Ent
    C_PLAY:           PLAY/ PAUSE
    C_PREV:           PREV ←
    C_NEXT:           NEXT →
    BT_CLR:           CLEAR

    UP:               ↑
    DOWN:             ↓
    LEFT:             ←
    RIGHT:            →

    # defaults
    AMPS:             '&'
    AT:               '"' # UK
    DQT:              '@' # UK
    BSLH:             \
    CAPS:             Caps
    CARET:            ^
    COLON:            ':'
    COMMA:            ','
    DOT:              '.'
    EQUAL:            '='
    EXCL:             '!'
    FSLH:             /
    GRAVE:            '`'
    GT:               '>'
    HASH:             '#'
    LBKT:             '['
    LBRC:             '{'
    LPAR:             (
    LT:               <
    MINUS:            '-'
    PERCENT:          '%'
    PIPE:             '|'
    PLUS:             +
    PRCNT:            '%'
    QMARK:            '?'
    RBKT:             ']'
    RBRC:             '}'
    RPAR:             )
    SEMI:             ;
    SQT:              ''''
    STAR:             '*'
    TILDE2:           '~'
    UNDER:            _

draw_config:
  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  dark_mode: false

  # Custom CSS
  svg_extra_style: |
    .ghost {
      display: none !important;
    }