parse_config:
  raw_binding_map:
    '&bootloader':    BOOT
    '&soft_off':      SOFT OFF
    '&caps_word':     Caps Word
    '&macro_grave3':  '```'
    '&macro_nequal':  <  >
    '&trans':         ''
    '&none':          {type: ghost}
    '&lt NAV SPACE':  {t: SPACE, h: NAV}
    '&lt NUM E':      {t: E, h: NUM}

    # navigation
    NAV_SEL_AL:       SEL ALL
    NAV_SEL_LI:       SEL LINE
    NAV_TAB_LE:       PREV TAB
    NAV_TAB_RI:       NEXT TAB
    NAV_CUT:          CUT
    NAV_COPY:         {t: COPY, h: R Shift}
    NAV_PASTE:        PASTE
    NAV_TAB:          {t: TAB, h: Ctrl}
    NAV_SWAP:         {t: SWAP, h: Shift}
    NAV_INCOG:        {t: INCOG, h: Alt}
    NAV_ARC:          {t: ARC, h: Win}
    NAV_CLO_TAB:      CLOSE TAB
    NAV_TAB_RO:       REOPEN TAB
    NAV_TAB_NE:       NEW TAB
    NAV_CLO_APP:      CLOSE APP
    NAV_SMILEY:       SMILEY
    NAV_DELWRD:       DEL WORD
    NAV_SWI_LE:       SWITCH LEFT
    NAV_SWI_RI:       SWITCH RIGHT
    NAV_THREAD:       SLACK THREAD        

    # number
    NUM_MINUS:        {t: MINUS, h: Ctrl}
    NUM_UNDER:        {t: UNDER, h: Shift}
    NUM_STAR:         {t: STAR, h: Alt}
    NUM_PERCENT:      {t: PERCENT, h: Win}

    # miscellaneous
    MIS_VOL_DN:       VOL DOWN
    MIS_VOL_MU:       VOL MUTE
    MIS_VOL_UP:       VOL UP
    MIS_MUT_MIC:      MIC MUTE
    MIS_BT_1:         BT  1
    MIS_BT_2:         BT  2
    MIS_BT_3:         BT  3
    MIS_SCREEN:       SCREEN SHOT
    MIS_CAD:          C  A  D
    MIS_BRI_DN:       BRI DOWN
    MIS_BRI_UP:       BRI UP
    MIS_BITWAR:       BIT WAR 
    MIS_GENERAT:      GEN PWD

    # UK symbols
    UK_HASH:          '#'
    UK_DQT:           '"'
    UK_AT:            '@'
    UK_GRAVE:         '`'
    UK_POUND:         {t: £, h: €}

  zmk_keycode_map:
    LCTL:             Ctrl
    LALT:             Alt
    LGUI:             Win
    LSFT:             Shift
    RSFT:             R Shift
    ESC:              Esc

    F2:               RENAME
    F6:               URL BAR
    F11:              FULL SCREEN
    F12:              DEV TOOLS
    F24:              {type: held}

    ENTER:            Ent
    C_PLAY:           PLAY/ PAUSE
    C_PREV:           PREV ←
    C_NEXT:           NEXT →
    BT_CLR:           CLEAR

    UP:               ↑
    DOWN:             ↓
    LEFT:             ←
    RIGHT:            →

    # defaults
    AMPS:             '&'
    BSLH:             \
    CAPS:             Caps
    CARET:            ^
    COLON:            ':'
    COMMA:            ','
    DOLLAR:           $
    DOT:              '.'
    EQUAL:            '='
    EXCL:             '!'
    FSLH:             /
    GRAVE:            '`'
    GT:               '>'
    HASH:             '#'
    LBKT:             '['
    LBRC:             '{'
    LPAR:             (
    LT:               <
    MINUS:            '-'
    PERCENT:          '%'
    PIPE2:            '|'
    PLUS:             +
    POUND:            £
    PRCNT:            '%'
    QMARK:            '?'
    RBKT:             ']'
    RBRC:             '}'
    RPAR:             )
    SEMI:             ;
    SQT:              ''''
    STAR:             '*'
    TILDE2:           '~'
    UNDER:            _

draw_config:
  footer_text: 'Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>'
  dark_mode: false

  # Custom CSS
  svg_extra_style: |
    .ghost {
      display: none !important;
    }