parse_config:
  raw_binding_map:
    '&mm_sqt_sqt': "'"
    'REDO': 'REDO'
    'UNDO': 'UNDO' 
    'UK_AT': '"'
    'UK_DQT': '@'
    'UK_HASH': '#'
    'UK_POUND': '£'
    'GRAVE': '`'
    '&bootloader': 'BOOT LOADER'
    'CON_ONE': 'BT1'
    'CON_ONE': 'BT2'
    'CON_ONE': 'BT3'
    'CAD': 'C+A+D'
    'SCREEN_SHOT': 'SCREENSHOT'
    'DESK_L': 'DESKTOP L'
    'DESK_R': 'DESKTOP R'
    'KILL': 'KILL'
    'A_INBOX': 'INBOX'
    'A_SLACK': 'SLACK'
    'A_GLADMIN': 'GLADMIN'
    'A_BULLHORN': 'BULLHORN'
    'A_CALENDAR': 'CALENDAR'