parse_config:
  raw_binding_map:
    '&bootloader':  'BOOT'
    '&mm_new_tab':  'NEW TAB'
    '&mm_sqt_sqt':  "'"
    'A_BULLHORN':   'BH'
    'A_CALENDAR':   'CAL'
    'A_GLADMIN':    'ADMIN'
    'A_INBOX':      'INBOX'
    'A_SLACK':      'SLACK'
    'CAD':          'C+A+D'
    'CON_ONE':      'BT1'
    'CON_THREE':    'BT3'
    'CON_TWO':      'BT2'
    'DEL_WORD':     'DEL WORD'
    'DESK_L':       'DESK L'
    'DESK_R':       'DESK R'
    'KILL':         'KILL'
    'NEW_LINE':     'NEW LINE'
    'REDO':         'REDO'
    'SCREEN_SHOT':  'S SHOT'
    'SHO_APP_SEL':  'SWAPPER'
    'SHO_COPY':     'COPY'
    'SHO_CUT':      'CUT'
    'SHO_PASTE':    'PASTE'
    'SHO_SEL_ALL':  'SEL ALL'
    'SLACK_DN':     'SLACK DN'
    'SLACK_UP':     'SLACK UP'
    'TAB_NEXT':     'TAB NEXT'
    'TAB_PREV':     'TAB PREV'
    'UK_AT':        '"'
    'UK_DQT':       '@'
    'UK_HASH':      '#'
    'UK_POUND':     '£'
    'UNDO':         'UNDO' 
  zmk_keycode_map:
    'GRAVE': '`'
