parse_config:
  raw_binding_map:
    '&mm_sqt_sqt': "'"
    'REDO': 'REDO'
    'UNDO': 'UNDO' 
    'UK_AT': '"'
    'UK_DQT': '@'
    'UK_HASH': '#'
    'UK_POUND': '£'
    '&kp GRAVE': '`'
    '&bootloader': 'BOOT'
    'CON_ONE': 'BT1'
    'CON_TWO': 'BT2'
    'CON_THREE': 'BT3'
    'CAD': 'C+A+D'
    'SCREEN_SHOT': 'S SHOT'
    'DESK_L': 'DESK  L'
    'DESK_R': 'DESK R'
    'KILL': 'KILL'
    'A_INBOX': 'INBOX'
    'A_SLACK': 'SLACK'
    'A_GLADMIN': 'ADMIN'
    'A_BULLHORN': 'BH'
    'A_CALENDAR': 'CAL'
    'SLACK_DN': 'SLACK DN'
    'SLACK_UP': 'SLACK UP'
    'DEL_WORD': 'DEL WORD'
    'SEL ALL': 'SEL ALL'
    '&mm_new_tab': 'NEW TAB'
    'SHO_CUT': 'CUT'
    'SHO_COPY': 'COPY'
    'SHO_PASTE': 'PASTE'
    'SHO_ALL_SEL': 'SWAPPER'
    'NEW_LINE': 'NEW LINE'
    'TAB_PREV': 'TAB PREV'
    'TAB_NEXT': 'TAB NEXT'
