manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: forkedzmk
      url-base: https://github.com/nickconway/zmk
  projects:
    - name: zmk
      remote: zmk
      revision: leader-key
      import: app/west.yml
  self:
    path: config